server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: biykcode
    password: 123456
    url: jdbc:mysql://localhost:3306/money?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
mybatis:
  type-aliases-package: com.biykcode.studyjodamoney.model
  type-handlers-package: com.biykcode.studyjodamoney.handler
  configuration:
    map-underscore-to-camel-case: true
